[package]
name = "vain-purple-tiger"
version = "0.1.0"
authors = ["Samuel Vanderwaal <samuel.vanderwaal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
